/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Game: typeof import('./src/components/Game.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Modify: typeof import('./src/components/Modify.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    TAutoComplete: typeof import('tdesign-vue-next')['AutoComplete']
    TBaseTable: typeof import('tdesign-vue-next')['BaseTable']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCheckTagGroup: typeof import('tdesign-vue-next')['CheckTagGroup']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    THighlightOption: typeof import('tdesign-vue-next')['HighlightOption']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TTag: typeof import('tdesign-vue-next')['Tag']
  }
}
